# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4de3716ef199fcce0d3199f72eda56ac643984b39cc497510e9255258a8c70daf8689e4b25d7aa48e3cc8c2f24d328380f6f8c91771e6bcfc5e6e3432aafec14

test:
  secret_key_base: 1706d830d31ff6c163c64133a1f13fdb6cb29e4ffd15d5f9c0840812de6cb4ad7ac1da60a374c9db16c1d6e39de992c5ad04622beeb5b678f1d9c833f64beb34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
